<?php

namespace AppBundle\Repository;

/**
 * NiklasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiklasRepository extends \Doctrine\ORM\EntityRepository
{
}
